#!/bin/bash
set -e

DATADIR=$(readlink -f $1)
SCRIPTSDIR=$(readlink -f /usr/lib/aur-pkgbuild-tester-scripts)
TESTER=$(readlink -f $SCRIPTSDIR/default.sh)

if [ ! -z "$2" ]; then
    TESTER=$(readlink -f $2)
fi
if [ ! -d "$DATADIR" ]; then
    echo "First argument must be a directory"
    exit 1
fi

if [ -d "$TESTER" ]; then
    echo "Second argument must not be a directory"
    exit 1
fi
docker run --rm -it \
    -v "$DATADIR/:~/pkgdir" \
    -v "$TESTER:~/test.sh" \
    -v "$SCRIPTSDIR/:~/scripts" \
    archlinux/base \
    ~/entrypoint.sh
